apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rodan-demo-v5 
  janus-idp.io/tekton: rodan-demo-v5
  backstage.io/kubernetes-id: rodan-demo-v5
  backstage.io/kubernetes-namespace: rodan-demo 
  app.kubernetes.io/part-of: rodan-demo-v5
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml