apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rodan-demo-v5
  janus-idp.io/tekton: rodan-demo-v5
  backstage.io/kubernetes-id: rodan-demo-v5
  backstage.io/kubernetes-namespace: rodan-demo 
  app.kubernetes.io/part-of: rodan-demo-v5
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
