apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rodan-demo-v5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rodan-demo-v5 
  name: rodan-demo-v5
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rodan-demo-v5 
